//! Chat message and request/response types, shared by the (future) sync
//! and streaming chat APIs.

use serde::{Deserialize, Serialize};

/// The role of a chat message's author.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// A system prompt/instruction.
    System,
    /// A message from the end user.
    User,
    /// A message generated by the model.
    Assistant,
    /// The result of a tool call.
    Tool,
}

/// A single chat message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Who authored this message.
    pub role: Role,
    /// The message text.
    pub content: String,
}

impl Message {
    /// Creates a system message.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: Role::System,
            content: content.into(),
        }
    }

    /// Creates a user message.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: content.into(),
        }
    }

    /// Creates an assistant message.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: Role::Assistant,
            content: content.into(),
        }
    }
}

/// A chat completion request.
#[derive(Debug, Clone, Serialize)]
pub struct ChatRequest {
    /// Model identifier to run inference against.
    pub model: String,
    /// Conversation history, ending with the newest message.
    pub messages: Vec<Message>,
    /// Sampling temperature, if overriding the runtime default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,
    /// Maximum tokens to generate, if overriding the runtime default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
    /// Whether the response should be streamed as incremental chunks.
    pub stream: bool,
}

/// Token usage reported for a chat completion.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Usage {
    /// Tokens consumed by the prompt.
    pub prompt_tokens: u32,
    /// Tokens generated in the completion.
    pub completion_tokens: u32,
    /// Total tokens (`prompt_tokens + completion_tokens`).
    pub total_tokens: u32,
}

/// Inference performance metrics reported alongside a chat completion.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct InferenceMetrics {
    /// Generation throughput, in tokens/sec.
    pub tokens_per_second: f64,
    /// Time to first token, in milliseconds.
    pub time_to_first_token_ms: u64,
}

/// A complete (non-streamed) chat completion response.
#[derive(Debug, Clone, Deserialize)]
pub struct ChatResponse {
    /// Unique id of this completion.
    pub id: String,
    /// Model that produced the completion.
    pub model: String,
    /// The generated text.
    pub text: String,
    /// Token usage for this request.
    #[serde(default)]
    pub usage: Usage,
    /// Inference performance metrics for this request.
    #[serde(default)]
    pub metrics: InferenceMetrics,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn message_constructors_set_expected_role() {
        assert_eq!(Message::system("s").role, Role::System);
        assert_eq!(Message::user("u").role, Role::User);
        assert_eq!(Message::assistant("a").role, Role::Assistant);
    }

    #[test]
    fn chat_request_serializes_without_optional_fields() {
        let req = ChatRequest {
            model: "m".to_string(),
            messages: vec![Message::user("hi")],
            temperature: None,
            max_tokens: None,
            stream: false,
        };
        let json = serde_json::to_string(&req).unwrap();
        assert!(!json.contains("temperature"));
        assert!(!json.contains("max_tokens"));
    }
}
